#!/usr/bin/env python3
"""Generate rtl/rsqrt_seed_rom.v -- initial-guess table for the 1/sqrt unit.

The rsqrt unit normalises its argument to a mantissa m in [1,4) held as
Mm = m * 2^30 in 32 bits.  The top LUT_BITS bits of Mm index this ROM:

    idx  = Mm[31 : 32-LUT_BITS]      (idx >= 2^(LUT_BITS-2) because m >= 1)
    m    ~ (idx + 0.5) / 2^(LUT_BITS-2)
    seed = round(2^15 / sqrt(m))     in Q1.15, clamped to 2^15

Seeding with the bin centre halves the worst-case seed error versus using the
bin edge.  With LUT_BITS = 6 the seed carries ~7 correct bits; each
Newton-Raphson step doubles that, so 3 steps saturate the 30-bit working
precision.
"""
import math
import os

LUT_BITS = 6
OUT = os.path.join(os.path.dirname(__file__), "..", "rtl", "rsqrt_seed_rom.v")


def seed_table(lut_bits=LUT_BITS):
    n = 1 << lut_bits
    scale = 1 << (lut_bits - 2)          # idx/scale = m
    tbl = []
    for idx in range(n):
        m = (idx + 0.5) / scale
        if m < 1.0:                      # unreachable (m >= 1), fill safely
            m = 1.0
        v = int(round((1 << 15) / math.sqrt(m)))
        tbl.append(min(v, 1 << 15))
    return tbl


def worst_case_relative_error(lut_bits=LUT_BITS):
    tbl = seed_table(lut_bits)
    scale = 1 << (lut_bits - 2)
    worst = 0.0
    for idx in range(scale, 1 << lut_bits):        # m in [1,4)
        y0 = tbl[idx] / (1 << 15)
        for f in (0.0, 0.5, 0.999):
            m = (idx + f) / scale
            exact = 1.0 / math.sqrt(m)
            worst = max(worst, abs(y0 - exact) / exact)
    return worst


def main(out=OUT):
    tbl = seed_table()
    err = worst_case_relative_error()
    lines = [
        "// ---------------------------------------------------------------------------",
        "// rsqrt_seed_rom.v  -- GENERATED by model/gen_seed_rom.py, do not edit.",
        "//",
        "//   addr : top %d bits of the normalised mantissa Mm = m*2^30, m in [1,4)" % LUT_BITS,
        "//   data : round(2^15 / sqrt(m_centre))  in Q1.15",
        "//",
        "//   worst-case seed relative error = %.5f  (~%.1f correct bits)" % (err, -math.log2(err)),
        "// ---------------------------------------------------------------------------",
        "`default_nettype none",
        "",
        "module rsqrt_seed_rom #(",
        "    parameter integer LUT_BITS = %d" % LUT_BITS,
        ")(",
        "    input  wire [LUT_BITS-1:0] addr,",
        "    output reg  [15:0]         data",
        ");",
        "",
        "    always @* begin",
        "        case (addr)",
    ]
    for i, v in enumerate(tbl):
        lines.append("            6'd%-3d: data = 16'd%d;" % (i, v))
    lines += [
        "            default: data = 16'd32768;",
        "        endcase",
        "    end",
        "",
        "endmodule",
        "",
        "`default_nettype wire",
    ]
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s (%d entries, worst seed err %.5f => %.1f bits)"
          % (os.path.normpath(out), len(tbl), err, -math.log2(err)))


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=OUT)
    main(ap.parse_args().out)
