// ---------------------------------------------------------------------------
// rsqrt_seed_rom.v  -- GENERATED by model/gen_seed_rom.py, do not edit.
//
//   addr : top 6 bits of the normalised mantissa Mm = m*2^30, m in [1,4)
//   data : round(2^15 / sqrt(m_centre))  in Q1.15
//
//   worst-case seed relative error = 0.01526  (~6.0 correct bits)
// ---------------------------------------------------------------------------
`default_nettype none

module rsqrt_seed_rom #(
    parameter integer LUT_BITS = 6
)(
    input  wire [LUT_BITS-1:0] addr,
    output reg  [15:0]         data
);

    always @* begin
        case (addr)
            6'd0  : data = 16'd32768;
            6'd1  : data = 16'd32768;
            6'd2  : data = 16'd32768;
            6'd3  : data = 16'd32768;
            6'd4  : data = 16'd32768;
            6'd5  : data = 16'd32768;
            6'd6  : data = 16'd32768;
            6'd7  : data = 16'd32768;
            6'd8  : data = 16'd32768;
            6'd9  : data = 16'd32768;
            6'd10 : data = 16'd32768;
            6'd11 : data = 16'd32768;
            6'd12 : data = 16'd32768;
            6'd13 : data = 16'd32768;
            6'd14 : data = 16'd32768;
            6'd15 : data = 16'd32768;
            6'd16 : data = 16'd32268;
            6'd17 : data = 16'd31332;
            6'd18 : data = 16'd30474;
            6'd19 : data = 16'd29682;
            6'd20 : data = 16'd28949;
            6'd21 : data = 16'd28268;
            6'd22 : data = 16'd27632;
            6'd23 : data = 16'd27038;
            6'd24 : data = 16'd26481;
            6'd25 : data = 16'd25956;
            6'd26 : data = 16'd25462;
            6'd27 : data = 16'd24994;
            6'd28 : data = 16'd24552;
            6'd29 : data = 16'd24132;
            6'd30 : data = 16'd23733;
            6'd31 : data = 16'd23354;
            6'd32 : data = 16'd22992;
            6'd33 : data = 16'd22646;
            6'd34 : data = 16'd22315;
            6'd35 : data = 16'd21999;
            6'd36 : data = 16'd21695;
            6'd37 : data = 16'd21404;
            6'd38 : data = 16'd21124;
            6'd39 : data = 16'd20855;
            6'd40 : data = 16'd20596;
            6'd41 : data = 16'd20346;
            6'd42 : data = 16'd20106;
            6'd43 : data = 16'd19873;
            6'd44 : data = 16'd19649;
            6'd45 : data = 16'd19431;
            6'd46 : data = 16'd19221;
            6'd47 : data = 16'd19018;
            6'd48 : data = 16'd18821;
            6'd49 : data = 16'd18630;
            6'd50 : data = 16'd18444;
            6'd51 : data = 16'd18264;
            6'd52 : data = 16'd18090;
            6'd53 : data = 16'd17920;
            6'd54 : data = 16'd17755;
            6'd55 : data = 16'd17594;
            6'd56 : data = 16'd17438;
            6'd57 : data = 16'd17285;
            6'd58 : data = 16'd17137;
            6'd59 : data = 16'd16992;
            6'd60 : data = 16'd16851;
            6'd61 : data = 16'd16714;
            6'd62 : data = 16'd16579;
            6'd63 : data = 16'd16448;
            default: data = 16'd32768;
        endcase
    end

endmodule

`default_nettype wire
